name = "paxos"
defaultTargets = ["StarCore"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.29.0"

[[lean_lib]]
name = "StarCore"
globs = ["Star.+"]

[[lean_lib]]
name = "Star"

[[lean_lib]]
name = "StarExperimental"
globs = ["StarExperimental.BackwardGen", "StarExperimental.MI", "StarExperimental.BackwardSearch", "StarExperimental.BackwardTactic", "StarExperimental.Tatic", "StarExperimental.MI_Tactic", "StarExperimental.MI_backward_directly", "StarExperimental.SumListLemmas", "StarExperimental.MSI_def", "StarExperimental.MESI_def", "StarExperimental.MSI_flush_proof", "StarExperimental.MESI_flush_proof", "StarExperimental.MSI"]
