/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 08a23bcc-b707-45d1-81c7-a29d8b1e7f06

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have formalized the definitions and theorems provided in the input.
In response to the question about proving `enough_star` with weaker assumptions, I defined `relation_flush_weak`, which weakens `relation_flush` by requiring only that a flush state is reachable after reduction, rather than being preserved immediately.
I then proved `enoght_internal_weak` using this weaker assumption.
Finally, I proved `enough_star_weak`, which establishes the simulation result using `relation_flush_weak` instead of `relation_flush`, while keeping the other assumptions.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

@[simp] abbrev Star1.Rule (A : Type _) := A → A → Prop
@[simp] abbrev Star1.Method (A : Type _) (E : Type _) := A → E → A → Prop

structure Star1.ARS (I : Type _) where
  A : Type
  rules : I → Star1.Rule A

inductive Star1.trans {A} (rule : Star1.Rule A) : Star1.Rule A where
| step {a b c} : Star1.trans rule a b → rule b c → Star1.trans rule a c
| refl {a b} : rule a b → Star1.trans rule a b

def Star1.refl {A} (rule : Star1.Rule A) (s e : A) : Prop :=
  rule s e ∨ s = e

inductive Star1.trans_refl {A} (rule : Star1.Rule A) : Star1.Rule A where
| step {a b c} : rule a b → Star1.trans_refl rule b c → Star1.trans_refl rule a c
| refl {a} : Star1.trans_refl rule a a

inductive Star1.trans_refl2 {A} (rule : Star1.Rule A) : Star1.Rule A where
| step {a b c} : rule b c → Star1.trans_refl2 rule a b → Star1.trans_refl2 rule a c
| refl {a} : Star1.trans_refl2 rule a a

inductive Star1.counted_trans_refl {A} (rule : Star1.Rule A) : A → A → Nat → Prop where
| step {a b c n} : rule a b → Star1.counted_trans_refl rule b c n → Star1.counted_trans_refl rule a c (n+1)
| refl {a} : Star1.counted_trans_refl rule a a 0

def Star1.ARS.red_seq {I} (ars : Star1.ARS I) (i : I) : Star1.Rule ars.A := Star1.trans_refl (ars.rules i)

inductive Star1.ARS.indexed_red_seq {I} (ars : Star1.ARS I) : List I → Star1.Rule ars.A where
| step {i is a b c} : ars.rules i a b → Star1.ARS.indexed_red_seq ars is b c → Star1.ARS.indexed_red_seq ars (i :: is) a c
| refl {a} : Star1.ARS.indexed_red_seq ars [] a a

def Star1.union {A} (α β : Star1.Rule A) (s e : A) : Prop := α s e ∨ β s e
def Star1.inv {A} (α : Star1.Rule A) (s e : A) : Prop := α e s
def Star1.symm {A} (α : Star1.Rule A) : Star1.Rule A := Star1.union α (Star1.inv α)
def Star1.compose {A} (α β : Star1.Rule A) (s e : A) : Prop := ∃ s', α s s' ∧ β s' e

def Star1.commutes_weakly {A} (α β : Star1.Rule A) :=
  ∀ {a b c : A}, β a c → α a b → ∃ d, Star1.trans_refl α c d ∧ Star1.trans_refl β b d

def Star1.commutes {A} (α β : Star1.Rule A) := Star1.commutes_weakly (Star1.trans_refl α) (Star1.trans_refl β)

def Star1.weakly_confluent {A} (α : Star1.Rule A) := Star1.commutes_weakly α α

def Star1.is_subcommutative {A} (α : Star1.Rule A) :=
  ∀ {a b c : A}, α a c → α a b → ∃ d, Star1.refl α c d ∧ Star1.refl α b d

def Star1.has_diamond_property {A} (α : Star1.Rule A) :=
  ∀ {a b c : A}, α a c → α a b → ∃ d, α c d ∧ α b d

def Star1.is_confluent {A} (α : Star1.Rule A) := Star1.commutes α α

def Star1.is_nf {A} (α : Star1.Rule A) (a : A) : Prop :=
  ∀ b, ¬ α a b

def Star1.has_nf {A} (α : Star1.Rule A) (b : A) : Prop :=
  ∃ a, Star1.trans_refl α b a ∧ Star1.is_nf α a

def Star1.weakly_normalising {A} (α : Star1.Rule A) := ∀ a, Star1.has_nf α a

inductive Star1.strongly_normalising' {A} (α : Star1.Rule A) : A → Prop where
| step {a} : (∀ b, α a b → Star1.strongly_normalising' α b) → Star1.strongly_normalising' α a

def Star1.strongly_normalising {A} (α : Star1.Rule A) := ∀ a, Star1.strongly_normalising' α a

inductive Star1.well_founded' {A} (α : Star1.Rule A) : A → Prop where
| step {b} : (∀ a, α a b → Star1.well_founded' α a) → Star1.well_founded' α b

def Star1.well_founded {A} (α : Star1.Rule A) := ∀ a, Star1.well_founded' α a

def Star1.is_inductive {A} (α : Star1.Rule A) :=
  ∀ a b n, Star1.counted_trans_refl α a b n → ∃ a', Star1.trans_refl α b a'

def Star1.is_increasing {A} (sz : A → Nat) (α : Star1.Rule A) :=
  ∀ a b, α a b → sz a < sz b

inductive Star1.xor : Bool → Bool → Bool → Prop where
| t_rule {b} : Star1.xor true b (¬ b)
| f_rule {b} : Star1.xor false b b

def Star1.ars : Star1.ARS Bool where
  A := Bool
  rules := Star1.xor

example : Star1.ARS.indexed_red_seq Star1.ars [true, false, true] true true := by repeat constructor

@[simp]
theorem Star1.double_application_term {A} (α: Star1.Rule A) :
  ∀ {a b: A},  α a b -> Star1.trans_refl α a b := by
  intro a b h
  apply Star1.trans_refl.step
  exact h
  apply Star1.trans_refl.refl

@[simp]
theorem Star1.double_application_term' {A} (α: Star1.Rule A) :
  ∀ {a b: A},  α a b -> Star1.trans α a b := by
    -- By definition of Star1.trans, if α a b holds, then Star1.trans α a b holds by the_refl constructor.
    intros a b hab
    apply Star1.trans.refl hab

@[simp]
theorem Star1.double_application_term1 {A} (α: Star1.Rule A) :
  ∀ {a b: A},  Star1.trans_refl α a b -> Star1.trans_refl (Star1.trans_refl α) a b := by
  intro a b h
  induction h
  case step a b c h1 h2 ih =>
    have HH := Star1.double_application_term _ h1
    apply Star1.trans_refl.step HH ih
  case refl a =>
    apply Star1.trans_refl.refl

@[simp]
theorem Star1.double_application_term2 {A} (α: Star1.Rule A) :
  ∀ {a b: A},  Star1.trans_refl (Star1.trans_refl α) a b  -> Star1.trans_refl α a b := by
  intro a b h
  induction h
  . clear a b
    rename_i a b c h1 h2 h3
    clear h2
    induction h1
    . clear a b
      rename_i a b d e h1 h2
      specialize h2 h3
      constructor <;> assumption
    . assumption
  . apply Star1.trans_refl.refl

theorem Star1.termination {A} (α : Star1.Rule A) : Star1.strongly_normalising α → Star1.well_founded (Star1.inv α) := by
  intro h a
  specialize h a
  induction h
  case step a h1 ih =>
    apply Star1.well_founded'.step
    intro b h2
    specialize ih b h2
    assumption

theorem Star1.termination_steps' {A} (α : Star1.Rule A) : Star1.well_founded α -> Star1.well_founded (Star1.trans α) := by
  intro h a
  apply Star1.well_founded'.step
  specialize h a
  intro b h2
  induction h generalizing b
  . rename_i xa xb xc
    cases h2
    .
      -- Apply the hypothesis `xc` with the given hypotheses.
      apply xc _ ‹_› _ ‹_›
    . constructor
      grind

theorem Star1.Newmans_lemma {A} (α : Star1.Rule A) :
  Star1.strongly_normalising α → Star1.has_diamond_property α → Star1.is_confluent α := by
    intro h_strongly_normalising h_diamond_property
    have h_confluent : Star1.well_founded (Star1.inv α) := by
      exact?
    generalize_proofs at *; (
    contrapose! h_confluent with h_confluent
    generalize_proofs at *; (
    intro h
    obtain ⟨a, ha⟩ : ∃ a, ¬Star1.is_nf α a := by
      by_cases h_nf : ∀ a : A, Star1.is_nf α a <;> simp_all +decide [ Star1.is_confluent ] ; (
      -- If every element is a normal form, then the relation α must be empty.
      have h_empty : ∀ a b : A, ¬α a b := by
        exact?
      generalize_proofs at *; (
      refine' h_confluent _;
      intro a b c h₁ h₂; exact ⟨ b, by
        cases h₁ <;> aesop ( simp_config := { singlePass := true } ) ;, by
        exact Star1.trans_refl.refl ⟩ ;))
    generalize_proofs at *; (
    obtain ⟨b, hb⟩ : ∃ b, α a b := by
      exact not_forall_not.mp fun h => ha fun b hb => h b hb
    generalize_proofs at *; (
    induction' h a with a ha ih generalizing b ; simp_all +decide [ Star1.is_nf ];
    obtain ⟨ c, hc ⟩ := h_diamond_property hb hb; specialize ih b ( by tauto ) c; aesop;))))

def Star1.indistinguishability {A B E} (method_i : Star1.Method A E) (method_s : Star1.Method B E) (i : A) (s : B) : Prop := ∀ (i' : A) e, method_i i e i' -> ∃ s', method_s s e s'

inductive Star1.φ₀ {A B} (flush : A -> B -> Prop) (rule : Star1.Rule A) : A -> B -> Prop where
| base : ∀ (i : A) (s : B),
          flush i s ->
          Star1.φ₀ flush rule i s
| rule_step : ∀ (i i' : A) (s : B),
              Star1.φ₀ flush rule i' s ->
              Star1.trans_refl rule i i' ->
              Star1.φ₀ flush rule i s

def Star1.relation_flush {A B} (flush : A -> B -> Prop) (i i' : A) (s : B) (rule : Star1.Rule A) := flush i s -> Star1.trans_refl rule i i' -> flush i' s

def Star1.relation_flush_method {A B E} (flush : A -> B -> Prop) (rule : Star1.Rule A) (method_i : Star1.Method A E) (method_s : Star1.Method B E) (i i' : A) (s s' : B) (e : E) := flush i s -> method_i i e i' -> method_s s e s' ->
                                ∃ i'', Star1.trans_refl rule i' i'' ∧ flush i'' s'

def Star1.relation_method {A B E} (flush : A -> B -> Prop) (method_i : Star1.Method A E) (method_s : Star1.Method B E) (i i' : A) (s : B) (e : E) := flush i s -> method_i i e i' -> ∃ s', method_s s e s'

theorem Star1.enoght_internal {A B} (flush : A -> B -> Prop) (rule : Star1.Rule A) (i : A) (s : B) :
    (∀ i i' s, Star1.relation_flush flush i i' s rule ) ->
    Star1.φ₀ flush rule i s -> ∀ i', Star1.trans_refl rule i i' -> Star1.has_diamond_property (Star1.trans_refl rule) -> Star1.φ₀ flush rule i' s := by
      intro he hφ₀ i' hstep hconf
      induction hφ₀ generalizing i'
      . rename_i i s' h3
        constructor
        unfold Star1.relation_flush at *
        apply he <;> assumption
      . clear i s
        rename_i i i'' s h1 h2 h4
        unfold Star1.has_diamond_property at *
        specialize @hconf i i'' i' hstep h2
        cases hconf; rename_i d H; rcases H with ⟨H1, H2⟩
        specialize h4 d H2
        apply Star1.φ₀.rule_step _ d _ <;> try assumption

def Star1.commutes_weakly_methods_i {A E} (α : Star1.Method A E) :=
  ∀ {a b c : A} { e e' : E}, α a e c → α a e' b → ∃ d, α c e' d ∧  α b e d

def Star1.commutes_weakly_methods_s {B E} (α : Star1.Method B E) :=
  ∀ {a b c : B} { e e' : E}, α a e c → α a e' b → ∃ d, α c e' d ∧  α b e d

def Star1.commutes_weakly_method_rule {A E} (α : Star1.Method A E) ( β : Star1.Rule A) :=
  ∀ {a b c : A} { e : E}, Star1.trans_refl β a b → α a e c → ∃ d, α b e d ∧ Star1.trans_refl β c d

theorem Star1.indistinguisability_preservation {A B E} (flush : A -> B -> Prop) (rule : Star1.Rule A) (method_i : Star1.Method A E) (method_s : Star1.Method B E) (i : A) (s : B) :
    ( ∀ i i' s e, Star1.relation_method flush method_i method_s i i' s e) ->
    Star1.φ₀ flush rule i s -> Star1.commutes_weakly_method_rule method_i rule -> Star1.indistinguishability method_i method_s i s := by
      intro hm h1 h2
      induction h1
      . clear i s
        rename_i i s h3
        unfold Star1.indistinguishability
        intro i' e h4
        unfold Star1.relation_method at hm
        apply hm <;> assumption
      . clear i s
        rename_i i i' s h3 h4 h5
        unfold Star1.indistinguishability at *
        intro i'' e h6
        unfold Star1.commutes_weakly_method_rule at *
        specialize h2 h4 h6
        cases h2; rename_i d h2; cases h2; rename_i h2 h2'
        apply h5 <;> assumption

theorem Star1.enoght_external {A B E} (flush : A -> B -> Prop) (rule : Star1.Rule A) (method_i : Star1.Method A E) (method_s : Star1.Method B E) (i : A) (s : B) :
    ( ∀ i i' s s' e, Star1.relation_flush_method flush rule method_i method_s i i' s s' e) ->
    ( ∀ i i' s e, Star1.relation_method flush method_i method_s i i' s e) ->
    Star1.φ₀ flush rule i s ->
    Star1.commutes_weakly_method_rule method_i rule ->
    ∀ i' e, method_i i e i' ->
    ∃ (s' : B), method_s s e s' ∧ Star1.φ₀ flush rule i' s' := by
      intro hm hm' hφ₀ h1 i' e h4
      have hi := @Star1.indistinguisability_preservation _ _ E _ _ method_i method_s _ _ hm' hφ₀ h1
      induction hφ₀ generalizing i'
      . clear i s
        rename_i i s h5
        unfold Star1.indistinguishability at *
        specialize hi i' e h4
        cases hi; rename_i s' hi
        constructor; rotate_left
        . exact s'
        . constructor
          . assumption
          . unfold Star1.relation_flush_method at hm
            specialize hm i i' s s' e h5 h4 hi
            rcases hm with ⟨ i'', hm, Hm⟩
            apply Star1.φ₀.rule_step _ i''
            . constructor; assumption
            . assumption
      . clear i s
        rename_i i i'' s h5 h6 h7
        have hh {A E} := @h1 A E
        unfold Star1.commutes_weakly_method_rule at h1
        specialize @h1 i i'' i' e h6 h4
        cases h1; rename_i d h1; cases h1; rename_i h1 h1'
        have H' := @Star1.indistinguisability_preservation _ _ E _ _ method_i method_s _ _ hm' h5
        specialize h7 d h1 (by unfold Star1.commutes_weakly_method_rule at *; grind)
        cases h7; rename_i s' h7; rcases h7 with ⟨ h7, h7'⟩
        constructor; rotate_left; exact s'
        constructor
        . assumption
        . apply Star1.φ₀.rule_step _ d _ <;> try assumption

inductive Star1.star {A E} (method_i : Star1.Method A E) : A -> List E -> A -> Prop where
  | refl : forall s1, Star1.star method_i s1 [] s1
  | step : forall s1 s2 s3 l e1, Star1.star method_i s1 l s2 -> method_i s2 e1 s3 -> Star1.star method_i s1 (e1 :: l) s3

inductive Star1.star_extend {A E} (rule : Star1.Rule A) (method_i : Star1.Method A E) : A -> List E -> A -> Prop where
  | refl : ∀ s, Star1.star_extend rule method_i s [] s
  | step_int : ∀ s l s' s'' , Star1.star_extend rule method_i s l s' ->  Star1.trans_refl rule s' s'' -> Star1.star_extend rule method_i s l s''
  | step_ext : ∀ s l s' s'' e, Star1.star_extend rule method_i s l s' -> method_i s' e s'' -> Star1.star_extend rule method_i s (e :: l) s''

theorem Star1.enough_star {A B E} (flush : A -> B -> Prop) (rule : Star1.Rule A) (method_i : Star1.Method A E) (method_s : Star1.Method B E) (i i' : A) (s : B) (l : List E) :
  (∀ i i' s, Star1.relation_flush flush i i' s rule ) ->
  ( ∀ i i' s s' e, Star1.relation_flush_method flush rule method_i method_s i i' s s' e) ->
  ( ∀ i i' s e, Star1.relation_method flush method_i method_s i i' s e) ->
  Star1.has_diamond_property (Star1.trans_refl rule) ->
  Star1.commutes_weakly_method_rule method_i rule ->
  Star1.φ₀ flush rule i s -> Star1.star_extend rule method_i i l i' -> ∃ s', Star1.star method_s s l s' ∧ Star1.φ₀ flush rule i' s':= by
    intro hm hm' hm'' HH HHH h1 h2
    revert h1 s
    induction h2 <;> intro s
    . intro h3
      exact ⟨ s, Star1.star.refl s, h3⟩
    . rename_i l' i_1 i_2  h9 h7 hi
      intro h11
      have h10 := hi _ h11
      cases h10
      rename_i s_1 h1
      let ⟨H1, H2⟩ := h1
      have h2 :=  Star1.enoght_internal _ _ _ _ hm H2 _ h7 HH
      constructor; rotate_left
      . exact s_1
      . constructor <;> assumption
    . clear i'
      rename_i l' i' i'' e _ h2 h3
      intro h4
      have h5 := h3 _ h4
      cases h5
      rename_i s' h6
      have h7 := Star1.enoght_external _ _ _ method_s  _ _ hm' hm'' h6.right (by assumption) _ _ h2
      cases h7
      rename_i s2 h8
      cases h8
      rename_i h8 h8'
      rcases h6 with ⟨ h6, h6'⟩
      constructor; rotate_left
      . exact s2
      . constructor
        . apply Star1.star.step
          . exact h6
          . assumption
        . assumption

/-
We define a weaker version of relation_flush, called relation_flush_weak, which allows the flush property to be re-established after some further reduction steps, rather than immediately.
-/
def Star1.relation_flush_weak {A B} (flush : A -> B -> Prop) (i i' : A) (s : B) (rule : Star1.Rule A) :=
  flush i s -> Star1.trans_refl rule i i' -> ∃ i'', Star1.trans_refl rule i' i'' ∧ flush i'' s

/-
We prove enoght_internal_weak using the weaker assumption relation_flush_weak.
This theorem states that if we have the diamond property and relation_flush_weak, then φ₀ is preserved under reduction (in the sense that if φ₀ i s and i ->* i', then φ₀ i' s).
This is essentially saying that if i can reach a flush state, and i reduces to i', then i' can also reach a flush state (possibly different).
-/
theorem Star1.enoght_internal_weak {A B} (flush : A -> B -> Prop) (rule : Star1.Rule A) (i : A) (s : B) :
    (∀ i i' s, Star1.relation_flush_weak flush i i' s rule ) ->
    Star1.φ₀ flush rule i s -> ∀ i', Star1.trans_refl rule i i' -> Star1.has_diamond_property (Star1.trans_refl rule) -> Star1.φ₀ flush rule i' s := by
      intro he hφ₀ i' hstep hconf
      induction hφ₀ generalizing i'
      . rename_i i s' h3
        unfold Star1.relation_flush_weak at he
        specialize he i i' s' h3 hstep
        rcases he with ⟨i'', h1, h2⟩
        apply Star1.φ₀.rule_step _ i''
        . constructor; assumption
        . assumption
      . clear i s
        rename_i i i'' s h1 h2 h4
        unfold Star1.has_diamond_property at *
        specialize @hconf i i'' i' hstep h2
        cases hconf; rename_i d H; rcases H with ⟨H1, H2⟩
        specialize h4 d H2
        apply Star1.φ₀.rule_step _ d _ <;> try assumption

/-
We prove enough_star_weak using enoght_internal_weak and the other original assumptions.
This theorem shows that we can still prove the main result (simulation of star_extend by star) even with the weaker flush relation assumption, provided we use the corresponding weaker internal lemma.
-/
theorem Star1.enough_star_weak {A B E} (flush : A -> B -> Prop) (rule : Star1.Rule A) (method_i : Star1.Method A E) (method_s : Star1.Method B E) (i i' : A) (s : B) (l : List E) :
  (∀ i i' s, Star1.relation_flush_weak flush i i' s rule ) ->
  ( ∀ i i' s s' e, Star1.relation_flush_method flush rule method_i method_s i i' s s' e) ->
  ( ∀ i i' s e, Star1.relation_method flush method_i method_s i i' s e) ->
  Star1.has_diamond_property (Star1.trans_refl rule) ->
  Star1.commutes_weakly_method_rule method_i rule ->
  Star1.φ₀ flush rule i s -> Star1.star_extend rule method_i i l i' -> ∃ s', Star1.star method_s s l s' ∧ Star1.φ₀ flush rule i' s':= by
    intro hm hm' hm'' HH HHH h1 h2
    revert h1 s
    induction h2 <;> intro s
    . intro h3
      exact ⟨ s, Star1.star.refl s, h3⟩
    . rename_i l' i_1 i_2  h9 h7 hi
      intro h11
      have h10 := hi _ h11
      cases h10
      rename_i s_1 h1
      let ⟨H1, H2⟩ := h1
      have h2 :=  Star1.enoght_internal_weak _ _ _ _ hm H2 _ h7 HH
      constructor; rotate_left
      . exact s_1
      . constructor <;> assumption
    . clear i'
      rename_i l' i' i'' e _ h2 h3
      intro h4
      have h5 := h3 _ h4
      cases h5
      rename_i s' h6
      have h7 := Star1.enoght_external _ _ _ method_s  _ _ hm' hm'' h6.right (by assumption) _ _ h2
      cases h7
      rename_i s2 h8
      cases h8
      rename_i h8 h8'
      rcases h6 with ⟨ h6, h6'⟩
      constructor; rotate_left
      . exact s2
      . constructor
        . apply Star1.star.step
          . exact h6
          . assumption
        . assumption
